### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by robl2e** [lzyzsd/CircleProgress#6]
Can you add a license file to indicate the license this code falls under?

**Comment by stokito** [comment]
The only one license that doesn’t have issues is [0BSD](https://en.wikipedia.org/wiki/0BSD):


- It’s used by Google for Android part (Toybox) while the WTFPL is blocked.
- The BSD licenses are well known for corporate lawyers and they’ll be fine with it.
- It doesn’t mention the problematic Public Domain but it’s effectively it’s equivalent.
- It’s popular and used even more often WTFPL.
- It’s very short and doesn’t have many versions.
- It’s old and used since 2006

Please use the standard license to avoid fragmentation and confusing.
